require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DentalExaminationsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DentalExamination. As you add validations to DentalExamination, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DentalExaminationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dental_examinations as @dental_examinations" do
      dental_examination = DentalExamination.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dental_examinations)).to eq([dental_examination])
    end
  end

  describe "GET show" do
    it "assigns the requested dental_examination as @dental_examination" do
      dental_examination = DentalExamination.create! valid_attributes
      get :show, {:id => dental_examination.to_param}, valid_session
      expect(assigns(:dental_examination)).to eq(dental_examination)
    end
  end

  describe "GET new" do
    it "assigns a new dental_examination as @dental_examination" do
      get :new, {}, valid_session
      expect(assigns(:dental_examination)).to be_a_new(DentalExamination)
    end
  end

  describe "GET edit" do
    it "assigns the requested dental_examination as @dental_examination" do
      dental_examination = DentalExamination.create! valid_attributes
      get :edit, {:id => dental_examination.to_param}, valid_session
      expect(assigns(:dental_examination)).to eq(dental_examination)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DentalExamination" do
        expect {
          post :create, {:dental_examination => valid_attributes}, valid_session
        }.to change(DentalExamination, :count).by(1)
      end

      it "assigns a newly created dental_examination as @dental_examination" do
        post :create, {:dental_examination => valid_attributes}, valid_session
        expect(assigns(:dental_examination)).to be_a(DentalExamination)
        expect(assigns(:dental_examination)).to be_persisted
      end

      it "redirects to the created dental_examination" do
        post :create, {:dental_examination => valid_attributes}, valid_session
        expect(response).to redirect_to(DentalExamination.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dental_examination as @dental_examination" do
        post :create, {:dental_examination => invalid_attributes}, valid_session
        expect(assigns(:dental_examination)).to be_a_new(DentalExamination)
      end

      it "re-renders the 'new' template" do
        post :create, {:dental_examination => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dental_examination" do
        dental_examination = DentalExamination.create! valid_attributes
        put :update, {:id => dental_examination.to_param, :dental_examination => new_attributes}, valid_session
        dental_examination.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dental_examination as @dental_examination" do
        dental_examination = DentalExamination.create! valid_attributes
        put :update, {:id => dental_examination.to_param, :dental_examination => valid_attributes}, valid_session
        expect(assigns(:dental_examination)).to eq(dental_examination)
      end

      it "redirects to the dental_examination" do
        dental_examination = DentalExamination.create! valid_attributes
        put :update, {:id => dental_examination.to_param, :dental_examination => valid_attributes}, valid_session
        expect(response).to redirect_to(dental_examination)
      end
    end

    describe "with invalid params" do
      it "assigns the dental_examination as @dental_examination" do
        dental_examination = DentalExamination.create! valid_attributes
        put :update, {:id => dental_examination.to_param, :dental_examination => invalid_attributes}, valid_session
        expect(assigns(:dental_examination)).to eq(dental_examination)
      end

      it "re-renders the 'edit' template" do
        dental_examination = DentalExamination.create! valid_attributes
        put :update, {:id => dental_examination.to_param, :dental_examination => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dental_examination" do
      dental_examination = DentalExamination.create! valid_attributes
      expect {
        delete :destroy, {:id => dental_examination.to_param}, valid_session
      }.to change(DentalExamination, :count).by(-1)
    end

    it "redirects to the dental_examinations list" do
      dental_examination = DentalExamination.create! valid_attributes
      delete :destroy, {:id => dental_examination.to_param}, valid_session
      expect(response).to redirect_to(dental_examinations_url)
    end
  end

end
